### PR TITLE
Add vector drawable icon & monochrome icon.

### PR DESCRIPTION
**Pull request by ikanakova**
Added icons. I think the mipmap-* png icons can be deleted. I only deleted the drawable folders because Android Studio didn't generate those for me. I think the drawable-v21 folder is also useless and can be deleted.

### CODE REVIEW

**Comment by ikanakova** [comment]
In the ic_launcher_round.xml file in the mipmap-anydpi-v26 folder I forgot to add a line for the monochrome icon, but you can copy it from ic_launcher.xml or copy the whole xml and rename it.

**Comment by mateusz-bak** [comment]
I don't this this works.

I deleted the .png files
Added `<monochrome android:drawable="@drawable/ic_launcher_monochrome"/>` to `ic_launcher_round.xml`
Changed `launch_background` to `ic_launcher_background` in `values/styles.xml` and  `values-night/styles.xml`
Changed `launcher_icon` to `ic_launcher` in `AndroidManifest.xml`

And that's the outcome with clean build and app reinstall:
Screenshot_1707982962

**Comment by ikanakova** [comment]
I found that "[your app should target Android 13 (targetSdkVersion 33)](https://medium.com/@akshaynighot73/add-themed-icon-support-for-your-android-app-d1745cf0862f)", but the build.gradle says `targetSdkVersion flutter.targetSdkVersion`, so I don't know if this is the problem.

**Comment by ikanakova** [comment]
I edited the monochrome icon to contain only 1 color.

**Comment by mateusz-bak** [comment]
Still no monochrome icon 😞

**Comment by ikanakova** [comment]
Could this be related to the Flutter version? (I don't know anything about Flutter. 😞) Because adaptive icons are only available since version 0.9.3. For lower versions, the solution is to add the code to the pubspec.yaml file in the dependencies entry:

```
flutter_launcher_icons: 
   git:
     url: https://github.com/Davenchy/flutter_launcher_icons.git
     ref: fixMinSdkParseFlutter2.8
```

Source: https://blog.logrocket.com/create-adaptive-icons-flutter-launcher-icons/#using-flutter-launcher-icons-flutter

**Comment by ikanakova** [comment]
https://github.com/fluttercommunity/flutter_launcher_icons

**Comment by mateusz-bak** [comment]
It has nothing to do with Flutter now as we are playing with the native Android files.

And per the package `flutter_launcher_icons` it's much newer version than 0.9.3 (it is set to ^0.13.1) and it still does not support svg packages so I think we need to still pursue the native way.

And also I tried setting the `targetSdkVersion` to 33 but no difference.

**Comment by ikanakova** [comment]
I probably figured out where the bug was, I forgot to overwrite the icon name in AndroidManifest.xml

**Comment by mateusz-bak** [comment]
I did that before as mentioned in https://github.com/mateusz-bak/openreads/pull/469#issuecomment-1945525313

Are you trying the changes locally?

**Comment by ikanakova** [comment]
> I did that before as mentioned in [#469 (comment)](https://github.com/mateusz-bak/openreads/pull/469#issuecomment-1945525313)
> 
> Are you trying the changes locally?

Yes. For other apps, this has worked for me. I don't see what the problem is here. I desperately looked all over for the problem, that's why I went back to the manifest and forgot that it was already settled.

**Comment by mateusz-bak** [comment]
Closing as it is implemented in #515

**Pull request closed without merging**
