### PR TITLE
Overflow Issues fixed

### PR DESCRIPTION
**Pull request by th8m0z**
I have fixed two of the overflow issues I mentioned. 

Search Page:
Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 20 20 27

Statistics:
Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 20 30 33

I also turned up the accessibility font size by a lot so we can see if there are more issues, but I have not found any so far, except that the rest of the text of the "currently reading" tab is cut off. But I also don't know a good way to fix this, since it doesn't make sense to make it scrollable.

### CODE REVIEW

**Comment by mateusz-bak** [comment]
Great, just checked and I have 2 small comments:

Can you align the search filters to `start` not `center` ?
Simulator Screenshot - iPhone 15 - 2024-02-29 at 11 30 01

Also I see in your screenshot that the chart legend is misaligned, could fix that too?

**Comment by th8m0z** [comment]
Yes sure, but the chart legend should be end aligned right? Everything else would look a bit weird

**Comment by mateusz-bak** [comment]
> Yes sure, but the chart legend should be end aligned right? Everything else would look a bit weird

Correct

**Comment by th8m0z** [comment]
Done!

**Comment by mateusz-bak** [comment]
Looks good, thanks!

**Pull request merged**
